version: "3.8"
services:
  db:
    image: "microsoft/mssql-server-linux:2017-latest"
    container_name: db
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=ch@ri5m@
    ports:
      - "1433:1433"
    # volumes:
    #   - sqlvolume:/var/opt/mssql
    networks:
      - samplenetwork  
  rabbitmq: 
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: my-rabbit
    ports: 
      - 15672:15672
      - 5672:5672
    networks:   
      - samplenetwork
networks:
  samplenetwork:
    driver: bridge
